// Comprehensive In-Memory Data Store for GraminConnect with Expanded Crops

const mockDb = {
  users: [
    {
      id: '1',
      username: 'ram_kisan',
      name: 'Ram Singh',
      role: 'farmer',
      village: 'Gurha Barsal',
      district: 'Jaipur',
      state: 'Rajasthan',
      phone: '9876543210',
      password: 'password123',
      landHolding: '4.5 Bigha',
      primaryCrop: 'Wheat, Mustard, Jeera',
    },
    {
      id: '2',
      username: 'suresh_trader',
      name: 'Suresh Kumar',
      role: 'trader',
      village: 'Kotputli',
      district: 'Jaipur',
      state: 'Rajasthan',
      phone: '9822334455',
      password: 'password123',
      businessName: 'Suresh Mandi Traders',
    },
    {
      id: '3',
      username: 'admin',
      name: 'Dinesh Soni (Supervisor)',
      role: 'admin',
      village: 'Jaipur Head Office',
      district: 'Jaipur',
      state: 'Rajasthan',
      phone: '9900112233',
      password: 'adminpassword',
    }
  ],

  marketData: [
    // Grains (अनाज)
    {
      id: 'm1',
      commodity: 'Wheat (गेहूं - Sharbati)',
      category: 'Grains',
      price: 2480,
      minPrice: 2390,
      maxPrice: 2550,
      trend: '+2.4%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Jaipur Mandi',
      district: 'Jaipur',
      state: 'Rajasthan',
      arrivals: '850 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 12, // Quintals
      history: [2380, 2400, 2410, 2395, 2420, 2450, 2480]
    },
    {
      id: 'm2',
      commodity: 'Bajra / Pearl Millet (बाजरा)',
      category: 'Grains',
      price: 2250,
      minPrice: 2150,
      maxPrice: 2320,
      trend: '+1.1%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Alwar Mandi',
      district: 'Alwar',
      state: 'Rajasthan',
      arrivals: '620 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 9,
      history: [2200, 2190, 2210, 2220, 2230, 2240, 2250]
    },
    {
      id: 'm3',
      commodity: 'Barley / Jau (जौ)',
      category: 'Grains',
      price: 1980,
      minPrice: 1900,
      maxPrice: 2050,
      trend: '-0.5%',
      trendDirection: 'down',
      unit: 'Quintal (100 kg)',
      location: 'Chomu Mandi',
      district: 'Jaipur',
      state: 'Rajasthan',
      arrivals: '340 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 11,
      history: [2000, 1990, 1995, 1985, 1980, 1980, 1980]
    },
    {
      id: 'm4',
      commodity: 'Maize / Makka (मक्का - Desi)',
      category: 'Grains',
      price: 2100,
      minPrice: 2000,
      maxPrice: 2180,
      trend: '+0.8%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Udaipur Mandi',
      district: 'Udaipur',
      state: 'Rajasthan',
      arrivals: '480 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 10,
      history: [2050, 2070, 2080, 2090, 2100, 2100, 2100]
    },
    {
      id: 'm5',
      commodity: 'Paddy / Basmati Dhan (धान)',
      category: 'Grains',
      price: 3850,
      minPrice: 3700,
      maxPrice: 3980,
      trend: '+2.1%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Kota Mandi',
      district: 'Kota',
      state: 'Rajasthan',
      arrivals: '950 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 14,
      history: [3750, 3780, 3800, 3820, 3830, 3850, 3850]
    },
    {
      id: 'm6',
      commodity: 'Jowar / Sorghum (ज्वार)',
      category: 'Grains',
      price: 2800,
      minPrice: 2650,
      maxPrice: 2920,
      trend: '+1.5%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Ajmer Mandi',
      district: 'Ajmer',
      state: 'Rajasthan',
      arrivals: '210 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 7,
      history: [2700, 2720, 2750, 2780, 2790, 2800, 2800]
    },

    // Oilseeds (तिलहन)
    {
      id: 'm7',
      commodity: 'Mustard (सरसों - Black 42% Oil)',
      category: 'Oilseeds',
      price: 5720,
      minPrice: 5580,
      maxPrice: 5850,
      trend: '+1.8%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Bharatpur Mandi',
      district: 'Bharatpur',
      state: 'Rajasthan',
      arrivals: '1200 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 7.5,
      history: [5550, 5600, 5620, 5680, 5700, 5710, 5720]
    },
    {
      id: 'm8',
      commodity: 'Soybean (सोयाबीन - Yellow)',
      category: 'Oilseeds',
      price: 4480,
      minPrice: 4350,
      maxPrice: 4560,
      trend: '-0.9%',
      trendDirection: 'down',
      unit: 'Quintal (100 kg)',
      location: 'Kota Mandi',
      district: 'Kota',
      state: 'Rajasthan',
      arrivals: '780 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 6.5,
      history: [4550, 4520, 4510, 4500, 4490, 4480, 4480]
    },
    {
      id: 'm9',
      commodity: 'Groundnut / Moongfali (मूंगफली)',
      category: 'Oilseeds',
      price: 6450,
      minPrice: 6200,
      maxPrice: 6600,
      trend: '+3.2%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Bikaner Mandi',
      district: 'Bikaner',
      state: 'Rajasthan',
      arrivals: '1100 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 9,
      history: [6200, 6250, 6300, 6380, 6400, 6420, 6450]
    },
    {
      id: 'm10',
      commodity: 'Sesame / Til (तिल - White)',
      category: 'Oilseeds',
      price: 12500,
      minPrice: 11800,
      maxPrice: 13200,
      trend: '+4.5%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Pali Mandi',
      district: 'Pali',
      state: 'Rajasthan',
      arrivals: '150 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 2.5,
      history: [11800, 12000, 12100, 12300, 12400, 12500, 12500]
    },
    {
      id: 'm11',
      commodity: 'Castor Seed / Arandi (अरंडी)',
      category: 'Oilseeds',
      price: 5850,
      minPrice: 5700,
      maxPrice: 5980,
      trend: '+0.4%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Jalore Mandi',
      district: 'Jalore',
      state: 'Rajasthan',
      arrivals: '320 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 6,
      history: [5800, 5820, 5830, 5840, 5840, 5850, 5850]
    },

    // Pulses (दालें)
    {
      id: 'm12',
      commodity: 'Chickpeas / Desi Chana (चना)',
      category: 'Pulses',
      price: 6180,
      minPrice: 6050,
      maxPrice: 6300,
      trend: '+2.8%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Bikaner Mandi',
      district: 'Bikaner',
      state: 'Rajasthan',
      arrivals: '840 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 6,
      history: [5950, 6000, 6050, 6100, 6140, 6160, 6180]
    },
    {
      id: 'm13',
      commodity: 'Green Gram / Moong (मूंग - Shining)',
      category: 'Pulses',
      price: 7900,
      minPrice: 7600,
      maxPrice: 8150,
      trend: '+1.6%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Nagaur Mandi',
      district: 'Nagaur',
      state: 'Rajasthan',
      arrivals: '560 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 4,
      history: [7700, 7750, 7800, 7850, 7880, 7900, 7900]
    },
    {
      id: 'm14',
      commodity: 'Black Gram / Urad (उड़द)',
      category: 'Pulses',
      price: 7400,
      minPrice: 7150,
      maxPrice: 7600,
      trend: '-1.1%',
      trendDirection: 'down',
      unit: 'Quintal (100 kg)',
      location: 'Bhilwara Mandi',
      district: 'Bhilwara',
      state: 'Rajasthan',
      arrivals: '290 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 3.5,
      history: [7550, 7500, 7480, 7450, 7420, 7400, 7400]
    },
    {
      id: 'm15',
      commodity: 'Moth Bean (मोठ)',
      category: 'Pulses',
      price: 5900,
      minPrice: 5700,
      maxPrice: 6100,
      trend: '+0.9%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Jodhpur Mandi',
      district: 'Jodhpur',
      state: 'Rajasthan',
      arrivals: '410 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 3.2,
      history: [5800, 5830, 5850, 5880, 5900, 5900, 5900]
    },

    // Cash Crops & Spices (नकदी फसल एवं मसाले)
    {
      id: 'm16',
      commodity: 'Cumin Seed / Jeera (जीरा)',
      category: 'Cash Crops',
      price: 24500,
      minPrice: 23200,
      maxPrice: 25800,
      trend: '+5.4%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Unjha / Jodhpur Mandi',
      district: 'Jodhpur',
      state: 'Rajasthan',
      arrivals: '820 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 2.8,
      history: [23000, 23400, 23800, 24000, 24200, 24500, 24500]
    },
    {
      id: 'm17',
      commodity: 'Guar Seed (ग्वार बीज)',
      category: 'Cash Crops',
      price: 5320,
      minPrice: 5180,
      maxPrice: 5450,
      trend: '+1.2%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Gurha Barsal Local Hub',
      district: 'Jaipur',
      state: 'Rajasthan',
      arrivals: '350 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 4.5,
      history: [5200, 5240, 5280, 5300, 5310, 5320, 5320]
    },
    {
      id: 'm18',
      commodity: 'Cotton / Kapas (कपास - Medium Staple)',
      category: 'Cash Crops',
      price: 7150,
      minPrice: 6900,
      maxPrice: 7350,
      trend: '-0.6%',
      trendDirection: 'down',
      unit: 'Quintal (100 kg)',
      location: 'Sri Ganganagar Mandi',
      district: 'Ganganagar',
      state: 'Rajasthan',
      arrivals: '1450 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 6,
      history: [7250, 7220, 7200, 7180, 7160, 7150, 7150]
    },
    {
      id: 'm19',
      commodity: 'Isabgol / Psyllium Husk (ईसबगोल)',
      category: 'Cash Crops',
      price: 14800,
      minPrice: 14000,
      maxPrice: 15500,
      trend: '+3.6%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Barmer Mandi',
      district: 'Barmer',
      state: 'Rajasthan',
      arrivals: '240 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 3.0,
      history: [14200, 14400, 14500, 14650, 14750, 14800, 14800]
    },
    {
      id: 'm20',
      commodity: 'Fennel / Saunf (सौंफ)',
      category: 'Cash Crops',
      price: 11200,
      minPrice: 10500,
      maxPrice: 11800,
      trend: '+2.0%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Nagaur Mandi',
      district: 'Nagaur',
      state: 'Rajasthan',
      arrivals: '190 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 3.5,
      history: [10800, 10950, 11000, 11100, 11150, 11200, 11200]
    },
    {
      id: 'm21',
      commodity: 'Coriander / Dhaniya (धनिया - Green)',
      category: 'Cash Crops',
      price: 7600,
      minPrice: 7200,
      maxPrice: 7900,
      trend: '+1.5%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Kota Mandi',
      district: 'Kota',
      state: 'Rajasthan',
      arrivals: '610 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 5.0,
      history: [7400, 7450, 7500, 7550, 7580, 7600, 7600]
    },
    {
      id: 'm22',
      commodity: 'Garlic / Lahsun (लहसुन - Ooty Grade)',
      category: 'Cash Crops',
      price: 16500,
      minPrice: 15200,
      maxPrice: 17800,
      trend: '+6.2%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Chhabra / Kota Mandi',
      district: 'Kota',
      state: 'Rajasthan',
      arrivals: '890 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 15.0,
      history: [15200, 15600, 15900, 16100, 16300, 16500, 16500]
    },
    {
      id: 'm23',
      commodity: 'Onion / Pyaz (लाल प्याज)',
      category: 'Cash Crops',
      price: 2400,
      minPrice: 2200,
      maxPrice: 2600,
      trend: '+1.9%',
      trendDirection: 'up',
      unit: 'Quintal (100 kg)',
      location: 'Alwar Mandi',
      district: 'Alwar',
      state: 'Rajasthan',
      arrivals: '2100 Quintals',
      lastUpdated: new Date().toISOString(),
      avgYieldPerBigha: 45.0,
      history: [2300, 2320, 2350, 2380, 2390, 2400, 2400]
    }
  ],

  weatherData: {
    current: {
      location: 'Gurha Barsal, Rajasthan',
      district: 'Jaipur',
      temperature: 31,
      feelsLike: 33,
      condition: 'Sunny / Partly Cloudy',
      icon: '☀️',
      humidity: 38,
      windSpeed: '12 km/h',
      rainProbability: '5%',
      uvIndex: 'High (7)',
      soilMoisture: 'Moderate (42%)',
      sunrise: '05:58 AM',
      sunset: '06:54 PM',
      updatedAt: new Date().toLocaleTimeString()
    },
    forecast: [
      { day: 'Today', temp: '31°C / 20°C', condition: 'Sunny', rain: '5%', icon: '☀️' },
      { day: 'Tomorrow', temp: '32°C / 21°C', condition: 'Clear Sky', rain: '0%', icon: '🌤️' },
      { day: 'Wednesday', temp: '33°C / 22°C', condition: 'Partly Cloudy', rain: '15%', icon: '⛅' },
      { day: 'Thursday', temp: '30°C / 19°C', condition: 'Scattered Showers', rain: '65%', icon: '🌦️' },
      { day: 'Friday', temp: '29°C / 18°C', condition: 'Light Rain', rain: '40%', icon: '🌧️' }
    ],
    advisories: [
      {
        id: 'adv-1',
        title: 'Irrigation Scheduling (सिंचाई सलाह)',
        severity: 'info',
        text: 'Weather is expected to remain dry for next 48 hours. Suitable time for mustard and wheat crop irrigation.'
      },
      {
        id: 'adv-2',
        title: 'Pest & Insect Alert (कीट नियंत्रण)',
        severity: 'warning',
        text: 'Check for aphid infestation in mustard fields. Spray neem oil solution (5ml/liter) in morning hours if spotted.'
      },
      {
        id: 'adv-3',
        title: 'Rain Warning for Thursday (बारिश की चेतावनी)',
        severity: 'alert',
        text: 'Pre-monsoon / western disturbance expected on Thursday. Postpone any fertilizer broadcasting till weekend.'
      }
    ]
  },

  schemes: [
    {
      id: 'sch-1',
      name: 'PM Kisan Samman Nidhi (पीएम किसान सम्मान निधि)',
      category: 'Direct Income Support',
      benefit: '₹6,000 per year in 3 equal installments',
      eligibility: 'All small & marginal landholder farmer families',
      documents: ['Aadhaar Card', 'Land Khatauni / Jamabandi', 'Bank Passbook'],
      department: 'Ministry of Agriculture & Farmers Welfare',
      deadline: 'Open all year',
      status: 'Active',
      officialUrl: 'https://pmkisan.gov.in/RegistrationFormNew.aspx',
      portalName: 'PM-KISAN Official Portal (pmkisan.gov.in)'
    },
    {
      id: 'sch-2',
      name: 'Pradhan Mantri Fasal Bima Yojana - PMFBY (फसल बीमा)',
      category: 'Crop Insurance',
      benefit: 'Comprehensive risk coverage against crop loss due to drought, unseasonal rains, or hail',
      eligibility: 'All farmers growing notified crops in notified areas',
      documents: ['Aadhaar Card', 'Sowing Certificate', 'Land Record (Khasra No.)', 'Bank Account'],
      department: 'Department of Agriculture & Cooperation',
      deadline: '31st August for Kharif, 31st December for Rabi',
      status: 'Active',
      officialUrl: 'https://pmfby.gov.in/farmerRegistrationForm',
      portalName: 'PMFBY National Crop Insurance Portal'
    },
    {
      id: 'sch-3',
      name: 'PM-KUSUM Solar Agriculture Pump Scheme (सोलर पंप 60% सब्सिडी)',
      category: 'Solar Subsidy',
      benefit: 'Up to 60% government subsidy on standalone solar irrigation pumps (3HP / 5HP / 7.5HP)',
      eligibility: 'Individual farmers, farmer groups, water user associations',
      documents: ['Aadhaar Card', 'Land Ownership Proof', 'Bank Statement', 'Electricity NOC'],
      department: 'Ministry of New & Renewable Energy (MNRE) & RajKisan',
      deadline: 'Quarterly allotments',
      status: 'Active',
      officialUrl: 'https://rajkisan.rajasthan.gov.in/',
      portalName: 'RajKisan Sathi / PM-KUSUM Portal'
    },
    {
      id: 'sch-4',
      name: 'Rajasthan Tarbandi Yojana (खेत तारबंदी 50% अनुदान)',
      category: 'Farm Fencing Subsidy',
      benefit: '50% subsidy (up to ₹48,000) for wire fencing around field to protect crops from stray animals',
      eligibility: 'Individual farmer having minimum 1.5 Hectare (6 Bigha) land or group of farmers',
      documents: ['Aadhaar Card', 'Jamabandi Record', 'Jan Aadhaar Card'],
      department: 'Agriculture Department, Govt of Rajasthan',
      deadline: 'Annual budget allotment',
      status: 'Active',
      officialUrl: 'https://rajkisan.rajasthan.gov.in/',
      portalName: 'RajKisan Portal (राजकिसान साथी)'
    },
    {
      id: 'sch-5',
      name: 'Soil Health Card Scheme (मृदा स्वास्थ्य कार्ड)',
      category: 'Soil Testing & Advisory',
      benefit: 'Free soil test report with customized fertilizer & NPK nutrient recommendations',
      eligibility: 'Open to all agricultural landholders',
      documents: ['Aadhaar Card', 'Khasra Details'],
      department: 'State Department of Agriculture, Rajasthan',
      deadline: 'Free on-demand testing',
      status: 'Active',
      officialUrl: 'https://soilhealth.dac.gov.in/',
      portalName: 'Soil Health Card National Portal'
    },
    {
      id: 'sch-6',
      name: 'Kisan Credit Card - KCC (किसान क्रेडिट कार्ड)',
      category: 'Low Interest Credit',
      benefit: 'Short term crop loans up to ₹3,00,000 at concessional interest rate of 4%',
      eligibility: 'Owner cultivators, tenant farmers, self-help groups',
      documents: ['Aadhaar Card', 'PAN Card', 'Land Possession Proof', 'Passport Photo'],
      department: 'NABARD & Commercial / Regional Rural Banks',
      deadline: 'Ongoing',
      status: 'Active',
      officialUrl: 'https://myscheme.gov.in/schemes/kcc',
      portalName: 'MyScheme Govt Portal (KCC Application)'
    },
    {
      id: 'sch-7',
      name: 'Micro Irrigation Subsidy - Drip & Sprinkler (फव्वारा एवं ड्रिप संयंत्र)',
      category: 'Irrigation Equipment',
      benefit: 'Up to 70% subsidy for small & marginal farmers on Drip & Sprinkler systems',
      eligibility: 'Farmers having cultivable land with operational water source',
      documents: ['Jan Aadhaar', 'Land Jamabandi', 'Soil & Water Test Report'],
      department: 'Horticulture Department, Rajasthan',
      deadline: 'Continuous scheme',
      status: 'Active',
      officialUrl: 'https://rajkisan.rajasthan.gov.in/',
      portalName: 'Rajasthan Horticulture & Agriculture Portal'
    }
  ],

  applications: [
    {
      id: 'app-101',
      userId: '1',
      userName: 'Ram Singh',
      schemeId: 'sch-1',
      schemeName: 'PM Kisan Samman Nidhi',
      appliedAt: '2026-08-10',
      status: 'Approved',
      remarks: 'Documents verified by Gurha Barsal Gram Panchayat Patwari.'
    },
    {
      id: 'app-102',
      userId: '1',
      userName: 'Ram Singh',
      schemeId: 'sch-3',
      schemeName: 'PM-KUSUM Solar Agriculture Pump Scheme',
      appliedAt: '2026-08-18',
      status: 'Under Verification',
      remarks: 'Field site inspection scheduled for 28th August.'
    }
  ],

  forumPosts: [
    {
      id: 'post-1',
      author: 'Kailash Meena',
      village: 'Gurha Barsal',
      title: 'गेहूं में पीलापन आ रहा है, क्या उपचार करें? (Yellowing in Wheat leaves)',
      content: 'Hello kisan bhaiyo, mere khet me gehu ke patte peele pad rahe hain. Kripya koi accha upchar batayein.',
      category: 'Crop Health',
      likes: 12,
      replies: [
        {
          id: 'rep-1',
          author: 'Dr. R.K. Sharma (Krishi Vigyan Kendra)',
          text: 'Ye Nitrogen ki kami ya Zinc ki kami ho sakti hai. 1 Bigha me 500g Zinc Sulphate (33%) aur 2.5kg Urea ko 100 liter paani me ghol kar chhidkaav karein.',
          isExpert: true,
          date: '2 hours ago'
        }
      ],
      createdAt: '5 hours ago'
    },
    {
      id: 'post-2',
      author: 'Mukesh Choudhary',
      village: 'Amer',
      title: 'Best time for harvesting Mustard in Rajasthan?',
      content: 'Pod color is turning yellow-brown. Is it ready for harvest this week?',
      category: 'Harvesting',
      likes: 8,
      replies: [
        {
          id: 'rep-2',
          author: 'Suresh Kumar',
          text: 'Jab 75-80% pods golden brown ho jayein tab harvest kar lein. Subah ke samay katai karein taaki daane na bikhrein.',
          isExpert: false,
          date: '1 day ago'
        }
      ],
      createdAt: '1 day ago'
    }
  ],

  // 🌾 Kisan Direct Marketplace (किसान बाजार / Direct Crop Sale)
  marketplaceListings: [
    {
      id: 'prod-1',
      farmerName: 'Ram Singh',
      crop: 'Wheat (गेहूं - Sharbati)',
      variety: 'Sharbati Organic Grade',
      quantityQuintals: 120,
      expectedPricePerQ: 2550,
      village: 'Gurha Barsal',
      district: 'Jaipur',
      phone: '9876543210',
      description: 'Cleaned, graded, and moisture-tested Sharbati wheat directly from farm. Ready for immediate pickup.',
      date: '2026-08-22',
      status: 'Available'
    },
    {
      id: 'prod-2',
      farmerName: 'Kailash Meena',
      crop: 'Mustard (सरसों - 42% Oil)',
      variety: 'Pusa Bold High Oil',
      quantityQuintals: 65,
      expectedPricePerQ: 5800,
      village: 'Sambhar Lake Region',
      district: 'Jaipur',
      phone: '9876543212',
      description: 'High oil percentage bold black mustard seed harvest. Suitable for oil expellers.',
      date: '2026-08-23',
      status: 'Available'
    },
    {
      id: 'prod-3',
      farmerName: 'Deepak Choudhary',
      crop: 'Cumin Seed / Jeera (जीरा)',
      variety: 'GC-4 Export Quality',
      quantityQuintals: 25,
      expectedPricePerQ: 24800,
      village: 'Piparcity',
      district: 'Jodhpur',
      phone: '9876543215',
      description: 'Sun-dried premium green cumin. Direct sale without mandi commission fee.',
      date: '2026-08-24',
      status: 'Available'
    },
    {
      id: 'prod-4',
      farmerName: 'Mohan Lal Jat',
      crop: 'Garlic / Lahsun (लहसुन - Ooty Variety)',
      variety: 'Large Clove Grade A',
      quantityQuintals: 80,
      expectedPricePerQ: 16800,
      village: 'Chhabra',
      district: 'Kota',
      phone: '9876543218',
      description: 'Graded large clove white garlic with tight skin. Pickup available from farm warehouse.',
      date: '2026-08-24',
      status: 'Available'
    }
  ],

  // 🚜 Farm Equipment & Tractor Rental Hub (कृषि यंत्र किराया)
  equipmentRentals: [
    {
      id: 'eq-1',
      ownerName: 'Balram Jat',
      equipmentType: 'Tractor (Mahindra 575 DI 45HP)',
      category: 'Tractors',
      ratePerHour: 600,
      ratePerBigha: 450,
      village: 'Gurha Barsal',
      district: 'Jaipur',
      phone: '9876543220',
      description: 'Well-maintained tractor with experienced driver. Available for plowing, leveling, and trolley transport.',
      status: 'Available'
    },
    {
      id: 'eq-2',
      ownerName: 'Sita Ram Meena',
      equipmentType: 'Combine Harvester (Preet 987)',
      category: 'Harvesters',
      ratePerHour: 1800,
      ratePerBigha: 1200,
      village: 'Chomu Area',
      district: 'Jaipur',
      phone: '9876543222',
      description: 'Multi-crop combine harvester for Wheat, Mustard, and Bajra with zero grain wastage.',
      status: 'Available'
    },
    {
      id: 'eq-3',
      ownerName: 'Harish Gurjar',
      equipmentType: 'Laser Land Leveler (कंप्यूटर मांझा)',
      category: 'Land Preparation',
      ratePerHour: 900,
      ratePerBigha: 700,
      village: 'Amer',
      district: 'Jaipur',
      phone: '9876543225',
      description: 'Precision GPS laser leveler to save 30% irrigation water and achieve uniform crop growth.',
      status: 'Available'
    },
    {
      id: 'eq-4',
      ownerName: 'Jagdish Yadav',
      equipmentType: 'Automatic Seed-cum-Fertilizer Drill',
      category: 'Sowing Implements',
      ratePerHour: 500,
      ratePerBigha: 350,
      village: 'Gurha Barsal',
      district: 'Jaipur',
      phone: '9876543228',
      description: '9-tyne pneumatic seed drill for precise line sowing of wheat and gram with uniform depth.',
      status: 'Available'
    }
  ]
};

module.exports = mockDb;
